---

- name: Install dependencies
  apt: name="{{ item }}" state=installed
  with_items: ['git', 'bc']

- name: Create install directory
  file: path="{{ letsencrypt_install_dir }}" state=directory

- name: Clone git repository
  git: repo=https://github.com/letsencrypt/letsencrypt dest="{{ letsencrypt_install_dir }}"

- name: Run standalone to acquire initial certs
  command: "./letsencrypt-auto certonly --standalone --standalone-supported-challenges tls-sni-01 --agree-tos -m {{ domain_email }} -d {{ domain }}"
  args:
    creates: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
    chdir: "{{ letsencrypt_install_dir }}"