---

- name: Create letsencrypt autoupdate script
  template:
    src: updateCerts.sh.j2
    dest: "{{ update_cert_script_location }}"
    mode: 0700
  tags: ['renew-certs']

- name: Create cron entries to autoupdate certs
  cron:
    month: "1-12"
    day: 1
    hour: 2
    job: "{{ update_cert_script_location }}"
    state: present
    name: "update_ssl_certs"
  tags: ['renew-certs']

- name: Run Update script
  command: "{{ update_cert_script_location }}"
  become: yes
  tags: ['renew-certs']
